name: Build

on:
  push:
    branches: [ softify-test ]

env:
  KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
  ALIAS_NAME: ${{ secrets.ALIAS_NAME }}
  ALIAS_PASS: ${{ secrets.ALIAS_PASS }}

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: '1.8'

    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'

    - run: "sed 's/\\(dependencies:\\)/\\1\\n\\ \\ intl_utils:\\ ^1.6.2/' -i pubspec.yaml"
    - run: ls -al
    - run: flutter pub get
#   - run: flutter packages pub run build_runner build
    - run: flutter pub run intl_utils:generate
    - run: flutter test
    - run: flutter build apk --debug
    - run: ls -al

    - uses: actions/upload-artifact@master
      name: Upload output folder
      with:
        name: PixEz-flutter
        path: build/app/outputs

    - uses: actions/upload-artifact@master
      name: Upload app-release.apk
      with:
        name: app-release
        path: build/app/outputs/apk/release/app-release.apk
